In [2]:

# Run this cell to import pyspark and to define start_spark() and stop_spark()

import findspark

findspark.init()

import getpass
import pandas
import pyspark
import random
import re

from IPython.display import display, HTML
from pyspark import SparkContext
from pyspark.sql import SparkSession


# Constants used to interact with Azure Blob Storage using the hdfs command or Spark

global username

username = re.sub('@.*', '', getpass.getuser())


# Functions used below

def dict_to_html(d):
    """Convert a Python dictionary into a two column table for display.
    """

    html = []

    html.append(f'<table width="100%" style="width:100%; font-family: monospace;">')
    for k, v in d.items():
        html.append(f'<tr><td style="text-align:left;">{k}</td><td>{v}</td></tr>')
    html.append(f'</table>')

    return ''.join(html)


def show_as_html(df, n=10):
    """Leverage existing pandas jupyter integration to show a spark dataframe as html.
    
    Args:
        n (int): number of rows to show (default: 20)
    """

    display(df.limit(n).toPandas())

    
def display_spark():
    """Display the status of the active Spark session if one is currently running.
    """
    
    if 'spark' in globals() and 'sc' in globals():

        name = sc.getConf().get("spark.app.name")

        html = [
            f'<p><b>Spark</b></p>',
            f'<p>The spark session is <b><span style="color:green">active</span></b>, look for <code>{name}</code> under the running applications section in the Spark UI.</p>',
            f'<ul>',
            f'<li><a href="http://localhost:{sc.uiWebUrl.split(":")[-1]}" target="_blank">Spark Application UI</a></li>',
            f'</ul>',
            f'<p><b>Config</b></p>',
            dict_to_html(dict(sc.getConf().getAll())),
            f'<p><b>Notes</b></p>',
            f'<ul>',
            f'<li>The spark session <code>spark</code> and spark context <code>sc</code> global variables have been defined by <code>start_spark()</code>.</li>',
            f'<li>Please run <code>stop_spark()</code> before closing the notebook or restarting the kernel or kill <code>{name}</code> by hand using the link in the Spark UI.</li>',
            f'</ul>',
        ]
        display(HTML(''.join(html)))
        
    else:
        
        html = [
            f'<p><b>Spark</b></p>',
            f'<p>The spark session is <b><span style="color:red">stopped</span></b>, confirm that <code>{username} (notebook)</code> is under the completed applications section in the Spark UI.</p>',
            f'<ul>',
            f'<li><a href="http://mathmadslinux2p.canterbury.ac.nz:8080/" target="_blank">Spark UI</a></li>',
            f'</ul>',
        ]
        display(HTML(''.join(html)))


# Functions to start and stop spark

def start_spark(executor_instances=2, executor_cores=1, worker_memory=1, master_memory=1):
    """Start a new Spark session and define globals for SparkSession (spark) and SparkContext (sc).
    
    Args:
        executor_instances (int): number of executors (default: 2)
        executor_cores (int): number of cores per executor (default: 1)
        worker_memory (float): worker memory (default: 1)
        master_memory (float): master memory (default: 1)
    """

    global spark
    global sc

    cores = executor_instances * executor_cores
    partitions = cores * 4
    port = 4000 + random.randint(1, 999)

    spark = (
        SparkSession.builder
        .config("spark.driver.extraJavaOptions", f"-Dderby.system.home=/tmp/{username}/spark/")
        .config("spark.dynamicAllocation.enabled", "false")
        .config("spark.executor.instances", str(executor_instances))
        .config("spark.executor.cores", str(executor_cores))
        .config("spark.cores.max", str(cores))
        .config("spark.driver.memory", f'{master_memory}g')
        .config("spark.executor.memory", f'{worker_memory}g')
        .config("spark.driver.maxResultSize", "0")
        .config("spark.sql.shuffle.partitions", str(partitions))
        .config("spark.kubernetes.container.image", "madsregistry001.azurecr.io/hadoop-spark:v3.3.5-openjdk-8")
        .config("spark.kubernetes.container.image.pullPolicy", "IfNotPresent")
        .config("spark.kubernetes.memoryOverheadFactor", "0.3")
        .config("spark.memory.fraction", "0.1")
        .config("spark.app.name", f"{username} (notebook)")
        .getOrCreate()
    )
    sc = SparkContext.getOrCreate()
    
    display_spark()

    
def stop_spark():
    """Stop the active Spark session and delete globals for SparkSession (spark) and SparkContext (sc).
    """

    global spark
    global sc

    if 'spark' in globals() and 'sc' in globals():

        spark.stop()

        del spark
        del sc

    display_spark()


# Make css changes to improve spark output readability

html = [
    '<style>',
    'pre { white-space: pre !important; }',
    'table.dataframe td { white-space: nowrap !important; }',
    'table.dataframe thead th:first-child, table.dataframe tbody th { display: none; }',
    '</style>',
]
display(HTML(''.join(html)))

In [3]:

# Run this cell to start a spark session in this notebook

start_spark(executor_instances=2, executor_cores=1, worker_memory=4, master_memory=1)

Warning: Ignoring non-Spark config property: SPARK_DRIVER_BIND_ADDRESS
25/05/07 08:43:39 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
25/05/07 08:43:40 WARN Utils: Service 'sparkDriver' could not bind on port 7077. Attempting port 7078.
25/05/07 08:43:40 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.

In [4]:

import os
os.environ["HADOOP_ROOT_LOGGER"] = "ERROR,console"

# Question 1 - Explore the relevant datasets


## 1. List the Main Directory

In [5]:

# List msd dir files
!hdfs dfs -ls wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/

2025-05-07 08:44:12,829 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Found 4 items
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/genre
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/main
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile

## 2. List Inside Each Folder

In [6]:

# Audio
!hdfs dfs -ls wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio

# Genre
!hdfs dfs -ls wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/genre

# Main
!hdfs dfs -ls wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/main

# Tasteprofile
!hdfs dfs -ls wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile

2025-05-07 08:44:14,755 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Found 2 items
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features
2025-05-07 08:44:16,690 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Found 3 items
-rwxrwxrwx   1   11625230 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/genre/msd-MAGD-genreAssignment.tsv
-rwxrwxrwx   1    8820054 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/genre/msd-MASD-styleAssignment.tsv
-rwxrwxrwx   1   11140605 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/genre/msd-topMAGD-genreAssignment.tsv
2025-05-07 08:44:18,518 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Found 2 items
-rwxrwxrwx   1   58658141 2025-02-18 15:22 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/main/analysis.csv.gz
-rwxrwxrwx   1  124211304 2025-02-18 15:22 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/main/metadata.csv.gz
2025-05-07 08:44:20,345 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Found 2 items
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/mismatches
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv

In [7]:

# List files in audio/attributes
!hdfs dfs -ls wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes

# List files in audio/features
!hdfs dfs -ls wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features

2025-05-07 08:44:22,252 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Found 13 items
-rwxrwxrwx   1       1051 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-jmir-area-of-moments-all-v1.0.attributes.csv
-rwxrwxrwx   1        671 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-jmir-lpc-all-v1.0.attributes.csv
-rwxrwxrwx   1        484 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-jmir-methods-of-moments-all-v1.0.attributes.csv
-rwxrwxrwx   1        898 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-jmir-mfcc-all-v1.0.attributes.csv
-rwxrwxrwx   1        777 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-jmir-spectral-all-all-v1.0.attributes.csv
-rwxrwxrwx   1        777 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-jmir-spectral-derivatives-all-all-v1.0.attributes.csv
-rwxrwxrwx   1      12317 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-marsyas-timbral-v1.0.attributes.csv
-rwxrwxrwx   1       9990 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-mvd-v1.0.attributes.csv
-rwxrwxrwx   1       1390 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-rh-v1.0.attributes.csv
-rwxrwxrwx   1      34913 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-rp-v1.0.attributes.csv
-rwxrwxrwx   1       3942 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-ssd-v1.0.attributes.csv
-rwxrwxrwx   1       9990 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-trh-v1.0.attributes.csv
-rwxrwxrwx   1      28313 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-tssd-v1.0.attributes.csv
2025-05-07 08:44:24,147 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Found 13 items
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-area-of-moments-all-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-lpc-all-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-methods-of-moments-all-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-mfcc-all-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-spectral-all-all-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-spectral-derivatives-all-all-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-marsyas-timbral-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-mvd-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-rh-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-rp-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-ssd-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-trh-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-tssd-v1.0.csv

In [8]:

# List files inside the mismatches folder
!hdfs dfs -ls wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/mismatches

2025-05-07 08:44:26,067 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Found 2 items
-rwxrwxrwx   1      91342 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/mismatches/sid_matches_manually_accepted.txt
-rwxrwxrwx   1    2026182 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/mismatches/sid_mismatches.txt

##  3. Find the Size

In [9]:

# MSD total
!hdfs dfs -du -s -h wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/

# Main dataset size
!hdfs dfs -du -s -h wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/main

# Genre dataset size
!hdfs dfs -du -s -h wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/genre

# Audio dataset size
!hdfs dfs -du -s -h wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio

# Tasteprofile dataset size
!hdfs dfs -du -s -h wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile

2025-05-07 08:44:27,912 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
12.9 G  12.9 G  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd
2025-05-07 08:44:30,654 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
174.4 M  174.4 M  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/main
2025-05-07 08:44:32,532 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
30.1 M  30.1 M  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/genre
2025-05-07 08:44:34,442 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
12.2 G  12.2 G  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio
2025-05-07 08:44:36,941 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
490.4 M  490.4 M  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile


## Load each of the different types of datasets

### 1. Read MAIN dataset (metadata + analysis)

In [10]:

! hdfs dfs -ls wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/main/

2025-05-07 08:44:38,867 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Found 2 items
-rwxrwxrwx   1   58658141 2025-02-18 15:22 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/main/analysis.csv.gz
-rwxrwxrwx   1  124211304 2025-02-18 15:22 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/main/metadata.csv.gz

In [11]:

! hdfs dfs -du -h wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/main/

2025-05-07 08:44:40,705 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
55.9 M   55.9 M   wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/main/analysis.csv.gz
118.5 M  118.5 M  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/main/metadata.csv.gz

#### a. Metadata

In [61]:

# Metadata (CSV with header)
df_metadata = spark.read.option("header", "true").option("inferSchema", "true").csv("wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/main/metadata.csv.gz")
show_as_html(df_metadata, 5)

,analyzer_version,artist_7digitalid,artist_familiarity,artist_hotttnesss,artist_id,artist_latitude,artist_location,artist_longitude,artist_mbid,artist_name,artist_playmeid,genre,idx_artist_terms,idx_similar_artists,release,release_7digitalid,song_hotttnesss,song_id,title,track_7digitalid
0,None,4069,0.649822,0.394032,ARYZTJS1187B98C555,NaN,None,None,357ff05d-848a-44cf-b608-cb34b5701ae5,Faster Pussy cat,44895,None,0,0,Monster Ballads X-Mas,633681,0.5428987432910862,SOQMMHC12AB0180CB8,Silent Night,7032331
1,None,113480,0.439604,0.356992,ARMVN3U1187FB3A1EB,NaN,None,None,8d7ef530-a6fd-4f8f-b2e2-74aec765e0f9,Karkkiautomaatti,-1,None,0,0,Karkuteillä,145266,0.2998774882739778,SOVFVAK12A8C1350D9,Tanssi vaan,1514808
2,None,63531,0.643681,0.437504,ARGEKB01187FB50750,55.8578,"Glasgow, Scotland",-4.24251,3d403d44-36ce-465c-ad43-ae877e65adc4,Hudson Mohawke,-1,None,0,0,Butter,625706,0.6178709693948196,SOGTUKN12AB017F4F1,No One Could Ever,6945353
3,None,65051,0.448501,0.372349,ARNWYLR1187B9B2F9C,NaN,None,None,12be7648-7094-495f-90e6-df4189d68615,Yerba Brava,34000,None,0,0,De Culo,199368,None,SOBNYVR12A8C13558C,Si Vos Querés,2168257
4,None,158279,0.000000,0.000000,AREQDTE1269FB37231,NaN,None,None,None,Der Mystic,-1,None,0,0,Rene Ablaze Presents Winter Sessions,209038,None,SOHSBXH12A8C13B0DF,Tangle Of Aspens,2264873

In [62]:

df_metadata.printSchema()

root
 |-- analyzer_version: string (nullable = true)
 |-- artist_7digitalid: integer (nullable = true)
 |-- artist_familiarity: double (nullable = true)
 |-- artist_hotttnesss: double (nullable = true)
 |-- artist_id: string (nullable = true)
 |-- artist_latitude: double (nullable = true)
 |-- artist_location: string (nullable = true)
 |-- artist_longitude: string (nullable = true)
 |-- artist_mbid: string (nullable = true)
 |-- artist_name: string (nullable = true)
 |-- artist_playmeid: string (nullable = true)
 |-- genre: string (nullable = true)
 |-- idx_artist_terms: integer (nullable = true)
 |-- idx_similar_artists: integer (nullable = true)
 |-- release: string (nullable = true)
 |-- release_7digitalid: integer (nullable = true)
 |-- song_hotttnesss: string (nullable = true)
 |-- song_id: string (nullable = true)
 |-- title: string (nullable = true)
 |-- track_7digitalid: string (nullable = true)

In [14]:

# Main metadata
print("Metadata row count:", df_metadata.count())

[Stage 2:>                                                          (0 + 1) / 1]

Metadata row count: 1000000

#### b. Analysis

In [63]:

# Analysis with header
df_analysis = spark.read.option("header", "true").option("inferSchema", "true").csv("wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/main/analysis.csv.gz")
show_as_html(df_analysis)

,analysis_sample_rate,audio_md5,danceability,duration,end_of_fade_in,energy,idx_bars_confidence,idx_bars_start,idx_beats_confidence,idx_beats_start,...,key,key_confidence,loudness,mode,mode_confidence,start_of_fade_out,tempo,time_signature,time_signature_confidence,track_id
0,22050,aee9820911781c734e7694c5432990ca,0.0,252.05506,2.049,0.0,0,0,0,0,...,10,0.777,-4.829,0,0.688,236.635,87.002,4,0.940,TRMMMYQ128F932D901
1,22050,ed222d07c83bac7689d52753610a513a,0.0,156.55138,0.258,0.0,0,0,0,0,...,9,0.808,-10.555,1,0.355,148.660,150.778,1,0.000,TRMMMKD128F425225D
2,22050,96c7104889a128fef84fa469d60e380c,0.0,138.97098,0.000,0.0,0,0,0,0,...,7,0.418,-2.060,1,0.566,138.971,177.768,4,0.446,TRMMMRX128F93187D9
3,22050,0f7da84b6b583e3846c7e022fb3a92a2,0.0,145.05751,0.000,0.0,0,0,0,0,...,7,0.125,-4.654,1,0.451,138.687,87.433,4,0.000,TRMMMCH128F425532C
4,22050,228dd6392ad8001b0281f533f34c72fd,0.0,514.29832,0.000,0.0,0,0,0,0,...,5,0.097,-7.806,0,0.290,506.717,140.035,4,0.315,TRMMMWA128F426B589
5,22050,001717032b7105ee4de70f67bf7fba3e,0.0,816.53506,2.194,0.0,0,0,0,0,...,10,0.419,-21.420,1,0.581,811.799,90.689,4,0.158,TRMMMXN128F42936A5
6,22050,eb4f5cb71ff1e50a279d1872929cf6b4,0.0,212.37506,0.000,0.0,0,0,0,0,...,3,0.611,-4.931,0,0.627,206.629,101.450,1,0.960,TRMMMLR128F1494097
7,22050,c5eaa27a919d3403cb12745056de0b21,0.0,221.20444,0.165,0.0,0,0,0,0,...,11,0.332,-12.214,0,0.350,212.120,98.020,4,0.982,TRMMMBB12903CB7D21
8,22050,801588bb617e8dfb92df0465619f6a2c,0.0,139.17995,0.171,0.0,0,0,0,0,...,5,0.537,-10.705,1,0.523,130.479,115.427,1,0.324,TRMMMHY12903CB53F1
9,22050,766c396dfd07dc2cc956603f8efcb7d0,0.0,104.48934,0.000,0.0,0,0,0,0,...,4,0.668,-20.160,0,0.480,104.489,124.339,4,1.000,TRMMMML128F4280EE9

In [64]:

df_analysis.printSchema()

root
 |-- analysis_sample_rate: integer (nullable = true)
 |-- audio_md5: string (nullable = true)
 |-- danceability: double (nullable = true)
 |-- duration: double (nullable = true)
 |-- end_of_fade_in: double (nullable = true)
 |-- energy: double (nullable = true)
 |-- idx_bars_confidence: integer (nullable = true)
 |-- idx_bars_start: integer (nullable = true)
 |-- idx_beats_confidence: integer (nullable = true)
 |-- idx_beats_start: integer (nullable = true)
 |-- idx_sections_confidence: integer (nullable = true)
 |-- idx_sections_start: integer (nullable = true)
 |-- idx_segments_confidence: integer (nullable = true)
 |-- idx_segments_loudness_max: integer (nullable = true)
 |-- idx_segments_loudness_max_time: integer (nullable = true)
 |-- idx_segments_loudness_start: integer (nullable = true)
 |-- idx_segments_pitches: integer (nullable = true)
 |-- idx_segments_start: integer (nullable = true)
 |-- idx_segments_timbre: integer (nullable = true)
 |-- idx_tatums_confidence: integer (nullable = true)
 |-- idx_tatums_start: integer (nullable = true)
 |-- key: integer (nullable = true)
 |-- key_confidence: double (nullable = true)
 |-- loudness: double (nullable = true)
 |-- mode: integer (nullable = true)
 |-- mode_confidence: double (nullable = true)
 |-- start_of_fade_out: double (nullable = true)
 |-- tempo: double (nullable = true)
 |-- time_signature: integer (nullable = true)
 |-- time_signature_confidence: double (nullable = true)
 |-- track_id: string (nullable = true)

In [17]:

# Analysis
print("Analysis row count:", df_analysis.count())

[Stage 7:>                                                          (0 + 1) / 1]

Analysis row count: 1000000

### 2. Read GENRE datasets (MAGD + MASD + topMAGD)

In [18]:

!hdfs dfs -ls wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/genre/

2025-05-07 08:44:57,599 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Found 3 items
-rwxrwxrwx   1   11625230 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/genre/msd-MAGD-genreAssignment.tsv
-rwxrwxrwx   1    8820054 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/genre/msd-MASD-styleAssignment.tsv
-rwxrwxrwx   1   11140605 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/genre/msd-topMAGD-genreAssignment.tsv

In [19]:

!hdfs dfs -du -h wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/genre/msd-MAGD-genreAssignment.tsv
!hdfs dfs -du -h wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/genre/msd-MASD-styleAssignment.tsv
!hdfs dfs -du -h wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/genre/msd-topMAGD-genreAssignment.tsv

2025-05-07 08:44:59,448 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
11.1 M  11.1 M  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/genre/msd-MAGD-genreAssignment.tsv
2025-05-07 08:45:01,221 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
8.4 M  8.4 M  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/genre/msd-MASD-styleAssignment.tsv
2025-05-07 08:45:03,074 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
10.6 M  10.6 M  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/genre/msd-topMAGD-genreAssignment.tsv

#### a. MAGD

In [69]:

# MAGD Genre Assignment (TSV)
df_magd_genre = spark.read.option("header", "false").option("sep", "\t").option("inferSchema", "true") .csv('wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/genre/msd-MAGD-genreAssignment.tsv')
show_as_html(df_magd_genre)

                  _c0             _c1
0  TRAAAAK128F9318786        Pop_Rock
1  TRAAAAV128F421A322        Pop_Rock
2  TRAAAAW128F429D538             Rap
3  TRAAABD128F429CF47        Pop_Rock
4  TRAAACV128F423E09E        Pop_Rock
5  TRAAADT12903CCC339  Easy_Listening
6  TRAAAED128E0783FAB           Vocal
7  TRAAAEF128F4273421        Pop_Rock
8  TRAAAEM128F93347B9      Electronic
9  TRAAAFD128F92F423A        Pop_Rock

In [70]:
df_magd_genre.printSchema()

root
 |-- _c0: string (nullable = true)
 |-- _c1: string (nullable = true)

In [22]:

# MAGD Genre
print("MAGD Genre row count:", df_magd_genre.count())

MAGD Genre row count: 422714

#### MASD

In [71]:

# MASD Style Assignment (TSV)
df_masd_style = spark.read.option("header", "false").option("sep", "\t").option("inferSchema", "true").csv('wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/genre/msd-MASD-styleAssignment.tsv')
show_as_html(df_masd_style)

                  _c0                   _c1
0  TRAAAAK128F9318786     Metal_Alternative
1  TRAAAAV128F421A322                  Punk
2  TRAAAAW128F429D538           Hip_Hop_Rap
3  TRAAACV128F423E09E  Rock_Neo_Psychedelia
4  TRAAAEF128F4273421             Pop_Indie
5  TRAAAFP128F931B4E3           Hip_Hop_Rap
6  TRAAAGR128F425B14B      Pop_Contemporary
7  TRAAAHD128F42635A5             Rock_Hard
8  TRAAAHJ128F931194C             Pop_Indie
9  TRAAAHZ128E0799171           Hip_Hop_Rap

In [72]:

df_masd_style.printSchema()

root
 |-- _c0: string (nullable = true)
 |-- _c1: string (nullable = true)

In [25]:

# MASD Style
print("MASD Style row count:", df_masd_style.count())

MASD Style row count: 273936

#### c. Top MAGD

In [73]:

# Top MAGD Genre Assignment (TSV)
df_topmagd_genre = spark.read.option("header", "false").option("sep", "\t").option("inferSchema", "true").csv('wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/genre/msd-topMAGD-genreAssignment.tsv')
show_as_html(df_topmagd_genre)

                  _c0         _c1
0  TRAAAAK128F9318786    Pop_Rock
1  TRAAAAV128F421A322    Pop_Rock
2  TRAAAAW128F429D538         Rap
3  TRAAABD128F429CF47    Pop_Rock
4  TRAAACV128F423E09E    Pop_Rock
5  TRAAAED128E0783FAB       Vocal
6  TRAAAEF128F4273421    Pop_Rock
7  TRAAAEM128F93347B9  Electronic
8  TRAAAFD128F92F423A    Pop_Rock
9  TRAAAFP128F931B4E3         Rap

In [74]:

df_topmagd_genre.printSchema()

root
 |-- _c0: string (nullable = true)
 |-- _c1: string (nullable = true)

In [28]:

# Top MAGD Genre
print("Top MAGD Genre row count:", df_topmagd_genre.count())

Top MAGD Genre row count: 406427

### 3. Read AUDIO datasets (attributes + features)

In [29]:

!hdfs dfs -ls wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/

2025-05-07 08:45:07,660 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Found 2 items
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features

In [30]:

!hdfs dfs -du -h wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/

2025-05-07 08:45:09,609 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
103.0 K  103.0 K  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes
12.2 G   12.2 G   wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features

#### a. Attributes

In [31]:

# List all attribute description files in audio/attributes
!hdfs dfs -ls wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/

2025-05-07 08:45:12,153 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Found 13 items
-rwxrwxrwx   1       1051 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-jmir-area-of-moments-all-v1.0.attributes.csv
-rwxrwxrwx   1        671 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-jmir-lpc-all-v1.0.attributes.csv
-rwxrwxrwx   1        484 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-jmir-methods-of-moments-all-v1.0.attributes.csv
-rwxrwxrwx   1        898 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-jmir-mfcc-all-v1.0.attributes.csv
-rwxrwxrwx   1        777 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-jmir-spectral-all-all-v1.0.attributes.csv
-rwxrwxrwx   1        777 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-jmir-spectral-derivatives-all-all-v1.0.attributes.csv
-rwxrwxrwx   1      12317 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-marsyas-timbral-v1.0.attributes.csv
-rwxrwxrwx   1       9990 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-mvd-v1.0.attributes.csv
-rwxrwxrwx   1       1390 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-rh-v1.0.attributes.csv
-rwxrwxrwx   1      34913 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-rp-v1.0.attributes.csv
-rwxrwxrwx   1       3942 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-ssd-v1.0.attributes.csv
-rwxrwxrwx   1       9990 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-trh-v1.0.attributes.csv
-rwxrwxrwx   1      28313 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-tssd-v1.0.attributes.csv

In [75]:

# Example read for one attribute file
df_audio_attr = spark.read.option("header", "false").option("inferSchema", "true").csv('wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-jmir-mfcc-all-v1.0.attributes.csv')
show_as_html(df_audio_attr)

                                  _c0   _c1
0   MFCC_Overall_Standard_Deviation_1  real
1   MFCC_Overall_Standard_Deviation_2  real
2   MFCC_Overall_Standard_Deviation_3  real
3   MFCC_Overall_Standard_Deviation_4  real
4   MFCC_Overall_Standard_Deviation_5  real
5   MFCC_Overall_Standard_Deviation_6  real
6   MFCC_Overall_Standard_Deviation_7  real
7   MFCC_Overall_Standard_Deviation_8  real
8   MFCC_Overall_Standard_Deviation_9  real
9  MFCC_Overall_Standard_Deviation_10  real

In [76]:
df_audio_attr.printSchema()

root
 |-- _c0: string (nullable = true)
 |-- _c1: string (nullable = true)

In [34]:

# MFCC Audio Features
print("MFCC feature row count:", df_audio_attr.count())

MFCC feature row count: 27

#### b. Features

In [35]:

# List feature folders in audio/features
!hdfs dfs -ls wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/

2025-05-07 08:45:14,477 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Found 13 items
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-area-of-moments-all-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-lpc-all-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-methods-of-moments-all-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-mfcc-all-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-spectral-all-all-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-spectral-derivatives-all-all-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-marsyas-timbral-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-mvd-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-rh-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-rp-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-ssd-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-trh-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-tssd-v1.0.csv

In [36]:

# Example: List files in MFCC feature folder
!hdfs dfs -ls wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-mfcc-all-v1.0.csv

2025-05-07 08:45:16,412 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Found 8 items
-rwxrwxrwx   1    9325048 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-mfcc-all-v1.0.csv/part-00000.csv.gz
-rwxrwxrwx   1    9327316 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-mfcc-all-v1.0.csv/part-00001.csv.gz
-rwxrwxrwx   1    9324074 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-mfcc-all-v1.0.csv/part-00002.csv.gz
-rwxrwxrwx   1    9324094 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-mfcc-all-v1.0.csv/part-00003.csv.gz
-rwxrwxrwx   1    9324537 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-mfcc-all-v1.0.csv/part-00004.csv.gz
-rwxrwxrwx   1    9324133 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-mfcc-all-v1.0.csv/part-00005.csv.gz
-rwxrwxrwx   1    9322969 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-mfcc-all-v1.0.csv/part-00006.csv.gz
-rwxrwxrwx   1    8925237 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-mfcc-all-v1.0.csv/part-00007.csv.gz

In [37]:
# Example: List files in MFCC feature folder size
!hdfs dfs -du -h wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-mfcc-all-v1.0.csv

2025-05-07 08:45:18,292 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
8.9 M  8.9 M  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-mfcc-all-v1.0.csv/part-00001.csv.gz
8.9 M  8.9 M  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-mfcc-all-v1.0.csv/part-00003.csv.gz
8.9 M  8.9 M  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-mfcc-all-v1.0.csv/part-00005.csv.gz
8.5 M  8.5 M  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-mfcc-all-v1.0.csv/part-00007.csv.gz
8.9 M  8.9 M  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-mfcc-all-v1.0.csv/part-00002.csv.gz
8.9 M  8.9 M  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-mfcc-all-v1.0.csv/part-00006.csv.gz
8.9 M  8.9 M  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-mfcc-all-v1.0.csv/part-00004.csv.gz
8.9 M  8.9 M  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-mfcc-all-v1.0.csv/part-00000.csv.gz

In [78]:

# Read all MFCC example feature files
# Spark loads all 8 files automatically
df_audio_mfcc = spark.read.option("header", "false").option("inferSchema", "true").csv('wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-mfcc-all-v1.0.csv')

# Show first 5 rows
show_as_html(df_audio_mfcc, 10)

,_c0,_c1,_c2,_c3,_c4,_c5,_c6,_c7,_c8,_c9,...,_c17,_c18,_c19,_c20,_c21,_c22,_c23,_c24,_c25,_c26
0,59.28,4.150,5.105,2.275,2.185,1.950,1.603,1.335,1.300,1.396,...,1.0330,-0.3445,-0.4305,0.1372,0.0312,-0.3132,-0.0815,0.72130,-0.40500,'TRHFHQZ12903C9E2D5'
1,46.35,6.888,4.652,4.131,3.225,2.826,2.108,1.922,1.950,1.697,...,-0.2149,3.7400,0.2908,1.9200,0.1250,1.2420,-0.5187,0.25480,-0.40730,'TRHFHYX12903CAF953'
2,38.63,3.041,2.504,2.141,1.853,1.906,1.867,1.547,1.491,1.468,...,1.0350,1.2830,1.4080,0.5908,0.4882,0.5522,-0.3168,-0.58870,0.03743,'TRHFHAU128F9341A0E'
3,33.49,5.009,4.560,3.153,2.383,2.400,2.113,1.985,2.075,1.827,...,-1.3510,2.2640,-0.2145,0.3408,-0.6040,1.2610,-1.5270,0.02701,-0.73340,'TRHFHLP128F14947A7'
4,37.43,4.107,3.167,2.793,2.158,1.926,1.814,1.598,1.622,1.547,...,-1.0630,1.1670,0.0559,1.6820,-0.6607,1.0380,-0.1167,0.46200,-0.36870,'TRHFHFF128F930AC11'
5,39.64,6.211,4.122,3.262,2.768,2.745,2.464,2.407,2.666,2.013,...,0.8952,-1.5290,-2.0080,1.3750,-2.4640,1.0290,-1.0270,0.06470,-0.75020,'TRHFHYJ128F4234782'
6,56.25,3.235,2.330,2.095,1.754,1.723,1.608,1.496,1.497,1.466,...,-1.1980,-0.2131,-1.0130,-0.1782,-0.1977,0.4454,0.1277,-0.52250,-0.47130,'TRHFHHR128F9339010'
7,45.51,7.431,4.916,3.965,2.944,3.142,2.790,2.133,2.104,1.937,...,-0.8324,-0.3548,0.9817,-1.1610,-0.6234,-0.3629,-1.2830,-0.70310,-0.77060,'TRHFHMB128F4213BC9'
8,38.62,6.651,4.561,3.300,2.938,2.442,2.435,2.162,1.940,1.648,...,-1.1580,1.2790,-0.7887,0.8181,-0.2167,1.5400,-1.1880,0.79650,-0.63920,'TRHFHWT128F429032D'
9,46.05,6.799,3.876,3.552,2.802,2.655,2.463,2.354,2.181,2.109,...,2.1160,1.7510,0.9683,1.6640,0.5810,1.1340,-0.4208,0.58970,-0.43200,'TRHFHKO12903CBAF09'

In [79]:

df_audio_mfcc.printSchema()

root
 |-- _c0: double (nullable = true)
 |-- _c1: double (nullable = true)
 |-- _c2: double (nullable = true)
 |-- _c3: double (nullable = true)
 |-- _c4: double (nullable = true)
 |-- _c5: double (nullable = true)
 |-- _c6: double (nullable = true)
 |-- _c7: double (nullable = true)
 |-- _c8: double (nullable = true)
 |-- _c9: double (nullable = true)
 |-- _c10: double (nullable = true)
 |-- _c11: double (nullable = true)
 |-- _c12: double (nullable = true)
 |-- _c13: double (nullable = true)
 |-- _c14: double (nullable = true)
 |-- _c15: double (nullable = true)
 |-- _c16: double (nullable = true)
 |-- _c17: double (nullable = true)
 |-- _c18: double (nullable = true)
 |-- _c19: double (nullable = true)
 |-- _c20: double (nullable = true)
 |-- _c21: double (nullable = true)
 |-- _c22: double (nullable = true)
 |-- _c23: double (nullable = true)
 |-- _c24: double (nullable = true)
 |-- _c25: double (nullable = true)
 |-- _c26: string (nullable = true)

In [40]:

# MFCC Audio Features
print("MFCC feature row count:", df_audio_mfcc.count())

[Stage 32:=============================>                            (1 + 1) / 2]

MFCC feature row count: 994623

### 4. Read TASTEPROFILE datasets (triplets + mismatches)

In [41]:

!hdfs dfs -ls wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/

2025-05-07 08:45:24,112 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Found 2 items
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/mismatches
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv

In [42]:

!hdfs dfs -du -h wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/

2025-05-07 08:45:25,990 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
488.4 M  488.4 M  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv
2.0 M    2.0 M    wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/mismatches


#### a. Triplets

In [43]:

# List part files in tasteprofile triplets
!hdfs dfs -ls wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv

2025-05-07 08:45:27,936 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Found 8 items
-rwxrwxrwx   1   64020759 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv/part-00000.tsv.gz
-rwxrwxrwx   1   64038083 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv/part-00001.tsv.gz
-rwxrwxrwx   1   64077499 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv/part-00002.tsv.gz
-rwxrwxrwx   1   64102442 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv/part-00003.tsv.gz
-rwxrwxrwx   1   63998697 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv/part-00004.tsv.gz
-rwxrwxrwx   1   64049032 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv/part-00005.tsv.gz
-rwxrwxrwx   1   64064101 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv/part-00006.tsv.gz
-rwxrwxrwx   1   63788582 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv/part-00007.tsv.gz

In [44]:

!hdfs dfs -du -h wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv

2025-05-07 08:45:29,772 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
61.1 M  61.1 M  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv/part-00001.tsv.gz
61.1 M  61.1 M  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv/part-00003.tsv.gz
61.1 M  61.1 M  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv/part-00005.tsv.gz
61.1 M  61.1 M  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv/part-00006.tsv.gz
61.1 M  61.1 M  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv/part-00002.tsv.gz
60.8 M  60.8 M  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv/part-00007.tsv.gz
61.1 M  61.1 M  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv/part-00000.tsv.gz
61.0 M  61.0 M  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv/part-00004.tsv.gz

In [80]:

# Load main tasteprofile triplets
# Spark loads all 8 files automatically
df_triplets = spark.read.option("header", "false").option("sep", "\t").option("inferSchema", "true").csv('wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv')
show_as_html(df_triplets, 10)

                                        _c0                 _c1  _c2
0  f1bfc2a4597a3642f232e7a4e5d5ab2a99cf80e5  SOQEFDN12AB017C52B    1
1  f1bfc2a4597a3642f232e7a4e5d5ab2a99cf80e5  SOQOIUJ12A6701DAA7    2
2  f1bfc2a4597a3642f232e7a4e5d5ab2a99cf80e5  SOQOKKD12A6701F92E    4
3  f1bfc2a4597a3642f232e7a4e5d5ab2a99cf80e5  SOSDVHO12AB01882C7    1
4  f1bfc2a4597a3642f232e7a4e5d5ab2a99cf80e5  SOSKICX12A6701F932    1
5  f1bfc2a4597a3642f232e7a4e5d5ab2a99cf80e5  SOSNUPV12A8C13939B    1
6  f1bfc2a4597a3642f232e7a4e5d5ab2a99cf80e5  SOSVMII12A6701F92D    1
7  f1bfc2a4597a3642f232e7a4e5d5ab2a99cf80e5  SOTUNHI12B0B80AFE2    1
8  f1bfc2a4597a3642f232e7a4e5d5ab2a99cf80e5  SOTXLTZ12AB017C535    1
9  f1bfc2a4597a3642f232e7a4e5d5ab2a99cf80e5  SOTZDDX12A6701F935    1

In [81]:

df_triplets.printSchema()

root
 |-- _c0: string (nullable = true)
 |-- _c1: string (nullable = true)
 |-- _c2: integer (nullable = true)

In [47]:

# Tasteprofile Triplets
print("Triplets row count:", df_triplets.count())

[Stage 37:===========================================>              (3 + 1) / 4]

Triplets row count: 48373586

#### b. Mismatch

In [48]:

# List all files inside the tasteprofile/mismatches folder
!hdfs dfs -ls wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/mismatches/

2025-05-07 08:46:02,174 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Found 2 items
-rwxrwxrwx   1      91342 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/mismatches/sid_matches_manually_accepted.txt
-rwxrwxrwx   1    2026182 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/mismatches/sid_mismatches.txt

In [49]:

!hdfs dfs -du -h wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/mismatches/sid_matches_manually_accepted.txt
!hdfs dfs -du -h wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/mismatches/sid_mismatches.txt

2025-05-07 08:46:04,036 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
89.2 K  89.2 K  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/mismatches/sid_matches_manually_accepted.txt
2025-05-07 08:46:05,836 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
1.9 M  1.9 M  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/mismatches/sid_mismatches.txt

##### Manually accepted

In [82]:

# Load manually accepted matches 
df_accepted = spark.read.text("wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/mismatches/sid_matches_manually_accepted.txt")
show_as_html(df_accepted)

                                               value
0                                                9d8
1  < ERROR: <SOFQHZM12A8C142342 TRMWMFG128F92FFEF...
2                                              19d17
3  < ERROR: <SODXUTF12AB018A3DA TRMWPCD12903CCE5E...
4                                              29d26
5  < ERROR: <SOASCRF12A8C1372E6 TRMHIPJ128F426A2E...
6                                              33d29
7  < ERROR: <SOITDUN12A58A7AACA TRMHXGK128F42446A...
8                                              52d47
9  < ERROR: <SOLZXUM12AB018BE39 TRMRSOF12903CCF51...

In [83]:

df_accepted.printSchema()

root
 |-- value: string (nullable = true)

In [53]:

# Count rows in manually accepted matches
print("Rows in manually accepted matches:", df_accepted.count())

Rows in manually accepted matches: 938

##### Mismatches

In [54]:

# Load mismatch logs
df_mismatches = spark.read.text('wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/mismatches/sid_mismatches.txt')
show_as_html(df_mismatches)

                                               value
0  ERROR: <SOUMNSI12AB0182807 TRMMGKQ128F9325E10>...
1  ERROR: <SOCMRBE12AB018C546 TRMMREB12903CEB1B1>...
2  ERROR: <SOLPHZY12AC468ABA8 TRMMBOC12903CEB46E>...
3  ERROR: <SONGHTM12A8C1374EF TRMMITP128F425D8D0>...
4  ERROR: <SONGXCA12A8C13E82E TRMMAYZ128F429ECE6>...
5  ERROR: <SOMBCRC12A67ADA435 TRMMNVU128EF343EED>...
6  ERROR: <SOTDWDK12A8C13617B TRMMNCZ128F426FF0E>...
7  ERROR: <SOEBURP12AB018C2FB TRMMPBS12903CE90E1>...
8  ERROR: <SOSRJHS12A6D4FDAA3 TRMWMEL128F421DA68>...
9  ERROR: <SOIYAAQ12A6D4F954A TRMWHRI128F147EA8E>...

In [55]:

df_mismatches.printSchema()

root
 |-- value: string (nullable = true)

In [56]:

# Count rows in mismatches
print("Rows in mismatches:", df_mismatches.count())

Rows in mismatches: 19094

In [57]:

# Get row counts using Spark
metadata_count = df_metadata.count()
analysis_count = df_analysis.count()
magd_count = df_magd_genre.count()
masd_count = df_masd_style.count()
topmagd_count = df_topmagd_genre.count()
mfcc_attr_count = df_audio_attr.count()
mfcc_feat_count = df_audio_mfcc.count()
triplet_count = df_triplets.count()
accepted_count = df_accepted.count()
mismatches_count = df_mismatches.count()

# Create a summary list
row_counts = [
    ("Metadata", metadata_count),
    ("Analysis", analysis_count),
    ("MAGD Genre", magd_count),
    ("MASD Style", masd_count),
    ("Top MAGD Genre", topmagd_count),
    ("MFCC Attributes", mfcc_attr_count),
    ("MFCC Features", mfcc_feat_count),
    ("Triplets", triplet_count),
    ("Accepted Matches", accepted_count),
    ("Mismatches", mismatches_count)
]

# Convert to Pandas DataFrame (for display/export)
import pandas as pd
df_counts = pd.DataFrame(row_counts, columns=["Dataset", "Row Count"])

# display as a table (if using notebook)
from IPython.display import display
display(df_counts)

            Dataset  Row Count
0          Metadata    1000000
1          Analysis    1000000
2        MAGD Genre     422714
3        MASD Style     273936
4    Top MAGD Genre     406427
5   MFCC Attributes         27
6     MFCC Features     994623
7          Triplets   48373586
8  Accepted Matches        938
9        Mismatches      19094

In [60]:

# Count unique songs in each dataset using Spark
metadata_unique = df_metadata.select("song_id").distinct().count()
analysis_unique = df_analysis.select("track_id").distinct().count()
magd_unique = df_magd_genre.select("_c0").distinct().count()
masd_unique = df_masd_style.select("_c0").distinct().count()
topmagd_unique = df_topmagd_genre.select("_c0").distinct().count()
mfcc_unique_songs = df_audio_mfcc.select("_c26").distinct().count()
triplets_unique = df_triplets.select("_c1").distinct().count()


# Create summary list
unique_song_counts = [
    ("Metadata", metadata_unique),
    ("Analysis", analysis_unique),
    ("MAGD Genre", magd_unique),
    ("MASD Style", masd_unique),
    ("Top MAGD Genre", topmagd_unique),
    ("MFCC", mfcc_unique_songs),
    ("Triplets", triplets_unique)
    
]

# Convert to Pandas DataFrame for display
import pandas as pd
df_unique_songs = pd.DataFrame(unique_song_counts, columns=["Dataset", "Unique Songs"])

# Display the table 
from IPython.display import display
display(df_unique_songs)

          Dataset  Unique Songs
0        Metadata        998963
1        Analysis       1000000
2      MAGD Genre        422714
3      MASD Style        273936
4  Top MAGD Genre        406427
5            MFCC        994623
6        Triplets        384546

# Question 2 - Data preprocessing

In [111]:

from pyspark.sql.functions import col
from collections import Counter

# All attribute file paths
attribute_files = [
    "wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-jmir-area-of-moments-all-v1.0.attributes.csv",
    "wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-jmir-lpc-all-v1.0.attributes.csv",
    "wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-jmir-methods-of-moments-all-v1.0.attributes.csv",
    "wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-jmir-mfcc-all-v1.0.attributes.csv",
    "wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-jmir-spectral-all-all-v1.0.attributes.csv",
    "wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-jmir-spectral-derivatives-all-all-v1.0.attributes.csv",
    "wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-marsyas-timbral-v1.0.attributes.csv",
    "wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-mvd-v1.0.attributes.csv",
    "wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-rh-v1.0.attributes.csv",
    "wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-rp-v1.0.attributes.csv",
    "wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-ssd-v1.0.attributes.csv",
    "wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-trh-v1.0.attributes.csv",
    "wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-tssd-v1.0.attributes.csv"
]

# Counter for data types (case-sensitive)
type_counter = Counter()

# Loop through each attribute file and count data types
for path in attribute_files:
    df = spark.read.option("header", "false").csv(path)
    types = df.select(col("_c1")).rdd.flatMap(lambda x: x).filter(lambda x: x is not None).collect()
    type_counter.update(types)

# Display results
print("Data types found and their counts:")
for dtype, count in sorted(type_counter.items()):
    print(f"{dtype}: {count}")

Data types found and their counts:
NUMERIC: 3684
STRING: 6
real: 232
string: 7

In [97]:

from pyspark.sql.types import StructType, StructField, FloatType, StringType

# Mapping for attribute types
type_mapping = {
    "real": FloatType(),
    "numeric": FloatType(),
    "string": StringType()
}

# Function to build schema from attribute file
def create_audio_schema(attribute_path):
    df_attr = spark.read.option("header", "false").csv(attribute_path)

    schema_fields = []
    for row in df_attr.collect():
        attr_name = row["_c0"]
        attr_type = row["_c1"].lower()
        spark_type = type_mapping.get(attr_type, StringType())  # Default to StringType if unknown
        schema_fields.append(StructField(attr_name, spark_type, True))

    return StructType(schema_fields)

## Example 1: msd-jmir-mfcc-all-v1.0.attributes.csv

In [98]:

# Load the attribute file as a DataFrame
df_attr = spark.read.option("header", "false").csv('wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-jmir-mfcc-all-v1.0.attributes.csv')

# Show a few rows 
show_as_html(df_attr)

                                  _c0   _c1
0   MFCC_Overall_Standard_Deviation_1  real
1   MFCC_Overall_Standard_Deviation_2  real
2   MFCC_Overall_Standard_Deviation_3  real
3   MFCC_Overall_Standard_Deviation_4  real
4   MFCC_Overall_Standard_Deviation_5  real
5   MFCC_Overall_Standard_Deviation_6  real
6   MFCC_Overall_Standard_Deviation_7  real
7   MFCC_Overall_Standard_Deviation_8  real
8   MFCC_Overall_Standard_Deviation_9  real
9  MFCC_Overall_Standard_Deviation_10  real

In [99]:

df_attr.printSchema()

root
 |-- _c0: string (nullable = true)
 |-- _c1: string (nullable = true)

In [100]:

col_count = len(df_attr.columns)
print("Number of columns:", col_count)

Number of columns: 2

In [101]:

row_count = df_attr.count()
print("Number of rows:", row_count)

Number of rows: 27

In [102]:

# Load MFCC
mfcc_schema = create_audio_schema('wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-jmir-mfcc-all-v1.0.attributes.csv')
df_mfcc = load_audio_feature('wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-mfcc-all-v1.0.csv', mfcc_schema)

show_as_html(df_mfcc)

df_mfcc.printSchema()

,MFCC_Overall_Standard_Deviation_1,MFCC_Overall_Standard_Deviation_2,MFCC_Overall_Standard_Deviation_3,MFCC_Overall_Standard_Deviation_4,MFCC_Overall_Standard_Deviation_5,MFCC_Overall_Standard_Deviation_6,MFCC_Overall_Standard_Deviation_7,MFCC_Overall_Standard_Deviation_8,MFCC_Overall_Standard_Deviation_9,MFCC_Overall_Standard_Deviation_10,...,MFCC_Overall_Average_5,MFCC_Overall_Average_6,MFCC_Overall_Average_7,MFCC_Overall_Average_8,MFCC_Overall_Average_9,MFCC_Overall_Average_10,MFCC_Overall_Average_11,MFCC_Overall_Average_12,MFCC_Overall_Average_13,MSD_TRACKID
0,59.279999,4.150,5.105,2.275,2.185,1.950,1.603,1.335,1.300,1.396,...,1.0330,-0.3445,-0.4305,0.1372,0.0312,-0.3132,-0.0815,0.72130,-0.40500,'TRHFHQZ12903C9E2D5'
1,46.349998,6.888,4.652,4.131,3.225,2.826,2.108,1.922,1.950,1.697,...,-0.2149,3.7400,0.2908,1.9200,0.1250,1.2420,-0.5187,0.25480,-0.40730,'TRHFHYX12903CAF953'
2,38.630001,3.041,2.504,2.141,1.853,1.906,1.867,1.547,1.491,1.468,...,1.0350,1.2830,1.4080,0.5908,0.4882,0.5522,-0.3168,-0.58870,0.03743,'TRHFHAU128F9341A0E'
3,33.490002,5.009,4.560,3.153,2.383,2.400,2.113,1.985,2.075,1.827,...,-1.3510,2.2640,-0.2145,0.3408,-0.6040,1.2610,-1.5270,0.02701,-0.73340,'TRHFHLP128F14947A7'
4,37.430000,4.107,3.167,2.793,2.158,1.926,1.814,1.598,1.622,1.547,...,-1.0630,1.1670,0.0559,1.6820,-0.6607,1.0380,-0.1167,0.46200,-0.36870,'TRHFHFF128F930AC11'
5,39.639999,6.211,4.122,3.262,2.768,2.745,2.464,2.407,2.666,2.013,...,0.8952,-1.5290,-2.0080,1.3750,-2.4640,1.0290,-1.0270,0.06470,-0.75020,'TRHFHYJ128F4234782'
6,56.250000,3.235,2.330,2.095,1.754,1.723,1.608,1.496,1.497,1.466,...,-1.1980,-0.2131,-1.0130,-0.1782,-0.1977,0.4454,0.1277,-0.52250,-0.47130,'TRHFHHR128F9339010'
7,45.509998,7.431,4.916,3.965,2.944,3.142,2.790,2.133,2.104,1.937,...,-0.8324,-0.3548,0.9817,-1.1610,-0.6234,-0.3629,-1.2830,-0.70310,-0.77060,'TRHFHMB128F4213BC9'
8,38.619999,6.651,4.561,3.300,2.938,2.442,2.435,2.162,1.940,1.648,...,-1.1580,1.2790,-0.7887,0.8181,-0.2167,1.5400,-1.1880,0.79650,-0.63920,'TRHFHWT128F429032D'
9,46.049999,6.799,3.876,3.552,2.802,2.655,2.463,2.354,2.181,2.109,...,2.1160,1.7510,0.9683,1.6640,0.5810,1.1340,-0.4208,0.58970,-0.43200,'TRHFHKO12903CBAF09'

root
 |-- MFCC_Overall_Standard_Deviation_1: float (nullable = true)
 |-- MFCC_Overall_Standard_Deviation_2: float (nullable = true)
 |-- MFCC_Overall_Standard_Deviation_3: float (nullable = true)
 |-- MFCC_Overall_Standard_Deviation_4: float (nullable = true)
 |-- MFCC_Overall_Standard_Deviation_5: float (nullable = true)
 |-- MFCC_Overall_Standard_Deviation_6: float (nullable = true)
 |-- MFCC_Overall_Standard_Deviation_7: float (nullable = true)
 |-- MFCC_Overall_Standard_Deviation_8: float (nullable = true)
 |-- MFCC_Overall_Standard_Deviation_9: float (nullable = true)
 |-- MFCC_Overall_Standard_Deviation_10: float (nullable = true)
 |-- MFCC_Overall_Standard_Deviation_11: float (nullable = true)
 |-- MFCC_Overall_Standard_Deviation_12: float (nullable = true)
 |-- MFCC_Overall_Standard_Deviation_13: float (nullable = true)
 |-- MFCC_Overall_Average_1: float (nullable = true)
 |-- MFCC_Overall_Average_2: float (nullable = true)
 |-- MFCC_Overall_Average_3: float (nullable = true)
 |-- MFCC_Overall_Average_4: float (nullable = true)
 |-- MFCC_Overall_Average_5: float (nullable = true)
 |-- MFCC_Overall_Average_6: float (nullable = true)
 |-- MFCC_Overall_Average_7: float (nullable = true)
 |-- MFCC_Overall_Average_8: float (nullable = true)
 |-- MFCC_Overall_Average_9: float (nullable = true)
 |-- MFCC_Overall_Average_10: float (nullable = true)
 |-- MFCC_Overall_Average_11: float (nullable = true)
 |-- MFCC_Overall_Average_12: float (nullable = true)
 |-- MFCC_Overall_Average_13: float (nullable = true)
 |-- MSD_TRACKID: string (nullable = true)

### msd-jmir-mfcc-all-v1.0.attributes.csv Renamed

In [103]:

# Renaming logic
renamed_cols = []
for col_name in df_mfcc.columns:
    if "MFCC_Overall_Standard_Deviation_" in col_name:
        new_name = col_name.replace("MFCC_Overall_Standard_Deviation_", "mfcc_std_")
    elif "MFCC_Overall_Average_" in col_name:
        new_name = col_name.replace("MFCC_Overall_Average_", "mfcc_avg_")
    elif col_name == "MSD_TRACKID":
        new_name = "track_id"
    else:
        new_name = col_name
    renamed_cols.append((col_name, new_name))

# Apply renaming
for old_name, new_name in renamed_cols:
    df_mfcc = df_mfcc.withColumnRenamed(old_name, new_name)

# Show result
df_mfcc.printSchema()
show_as_html(df_mfcc)

root
 |-- mfcc_std_1: float (nullable = true)
 |-- mfcc_std_2: float (nullable = true)
 |-- mfcc_std_3: float (nullable = true)
 |-- mfcc_std_4: float (nullable = true)
 |-- mfcc_std_5: float (nullable = true)
 |-- mfcc_std_6: float (nullable = true)
 |-- mfcc_std_7: float (nullable = true)
 |-- mfcc_std_8: float (nullable = true)
 |-- mfcc_std_9: float (nullable = true)
 |-- mfcc_std_10: float (nullable = true)
 |-- mfcc_std_11: float (nullable = true)
 |-- mfcc_std_12: float (nullable = true)
 |-- mfcc_std_13: float (nullable = true)
 |-- mfcc_avg_1: float (nullable = true)
 |-- mfcc_avg_2: float (nullable = true)
 |-- mfcc_avg_3: float (nullable = true)
 |-- mfcc_avg_4: float (nullable = true)
 |-- mfcc_avg_5: float (nullable = true)
 |-- mfcc_avg_6: float (nullable = true)
 |-- mfcc_avg_7: float (nullable = true)
 |-- mfcc_avg_8: float (nullable = true)
 |-- mfcc_avg_9: float (nullable = true)
 |-- mfcc_avg_10: float (nullable = true)
 |-- mfcc_avg_11: float (nullable = true)
 |-- mfcc_avg_12: float (nullable = true)
 |-- mfcc_avg_13: float (nullable = true)
 |-- track_id: string (nullable = true)

,mfcc_std_1,mfcc_std_2,mfcc_std_3,mfcc_std_4,mfcc_std_5,mfcc_std_6,mfcc_std_7,mfcc_std_8,mfcc_std_9,mfcc_std_10,...,mfcc_avg_5,mfcc_avg_6,mfcc_avg_7,mfcc_avg_8,mfcc_avg_9,mfcc_avg_10,mfcc_avg_11,mfcc_avg_12,mfcc_avg_13,track_id
0,59.279999,4.150,5.105,2.275,2.185,1.950,1.603,1.335,1.300,1.396,...,1.0330,-0.3445,-0.4305,0.1372,0.0312,-0.3132,-0.0815,0.72130,-0.40500,'TRHFHQZ12903C9E2D5'
1,46.349998,6.888,4.652,4.131,3.225,2.826,2.108,1.922,1.950,1.697,...,-0.2149,3.7400,0.2908,1.9200,0.1250,1.2420,-0.5187,0.25480,-0.40730,'TRHFHYX12903CAF953'
2,38.630001,3.041,2.504,2.141,1.853,1.906,1.867,1.547,1.491,1.468,...,1.0350,1.2830,1.4080,0.5908,0.4882,0.5522,-0.3168,-0.58870,0.03743,'TRHFHAU128F9341A0E'
3,33.490002,5.009,4.560,3.153,2.383,2.400,2.113,1.985,2.075,1.827,...,-1.3510,2.2640,-0.2145,0.3408,-0.6040,1.2610,-1.5270,0.02701,-0.73340,'TRHFHLP128F14947A7'
4,37.430000,4.107,3.167,2.793,2.158,1.926,1.814,1.598,1.622,1.547,...,-1.0630,1.1670,0.0559,1.6820,-0.6607,1.0380,-0.1167,0.46200,-0.36870,'TRHFHFF128F930AC11'
5,39.639999,6.211,4.122,3.262,2.768,2.745,2.464,2.407,2.666,2.013,...,0.8952,-1.5290,-2.0080,1.3750,-2.4640,1.0290,-1.0270,0.06470,-0.75020,'TRHFHYJ128F4234782'
6,56.250000,3.235,2.330,2.095,1.754,1.723,1.608,1.496,1.497,1.466,...,-1.1980,-0.2131,-1.0130,-0.1782,-0.1977,0.4454,0.1277,-0.52250,-0.47130,'TRHFHHR128F9339010'
7,45.509998,7.431,4.916,3.965,2.944,3.142,2.790,2.133,2.104,1.937,...,-0.8324,-0.3548,0.9817,-1.1610,-0.6234,-0.3629,-1.2830,-0.70310,-0.77060,'TRHFHMB128F4213BC9'
8,38.619999,6.651,4.561,3.300,2.938,2.442,2.435,2.162,1.940,1.648,...,-1.1580,1.2790,-0.7887,0.8181,-0.2167,1.5400,-1.1880,0.79650,-0.63920,'TRHFHWT128F429032D'
9,46.049999,6.799,3.876,3.552,2.802,2.655,2.463,2.354,2.181,2.109,...,2.1160,1.7510,0.9683,1.6640,0.5810,1.1340,-0.4208,0.58970,-0.43200,'TRHFHKO12903CBAF09'

## Example 2: msd-rp-v1.0.attributes.csv

In [104]:

# Load the RP (Rhythm Patterns) attribute file
df_attr = spark.read.option("header", "false").csv("wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-rp-v1.0.attributes.csv")

# Show the first few rows
show_as_html(df_attr)

            _c0      _c1
0   component_1  NUMERIC
1   component_2  NUMERIC
2   component_3  NUMERIC
3   component_4  NUMERIC
4   component_5  NUMERIC
5   component_6  NUMERIC
6   component_7  NUMERIC
7   component_8  NUMERIC
8   component_9  NUMERIC
9  component_10  NUMERIC

In [105]:

# Load Rhythm Patterns (RP)
rp_schema = create_audio_schema('wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-rp-v1.0.attributes.csv')
df_rp = load_audio_feature('wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-rp-v1.0.csv', rp_schema)

show_as_html(df_rp)

# df_rp.printSchema()

,component_1,component_2,component_3,component_4,component_5,component_6,component_7,component_8,component_9,component_10,...,component_1432,component_1433,component_1434,component_1435,component_1436,component_1437,component_1438,component_1439,component_1440,instanceName
0,0.002736,0.003725,0.007415,0.002806,0.008469,0.007994,0.014948,0.008144,0.011970,0.013622,...,0.026226,0.017471,0.004238,0.009438,0.004225,0.005165,0.005210,0.003043,0.000001,TRYWDAH128F92D4539
1,0.001376,0.012098,0.004903,0.009153,0.009236,0.005353,0.003515,0.005018,0.006722,0.006616,...,0.007779,0.013003,0.012642,0.009386,0.005285,0.003885,0.002716,0.000712,0.000001,TRJVUJL128C71968F1
2,0.006036,0.006173,0.007350,0.008331,0.007874,0.008664,0.007132,0.008543,0.006113,0.007539,...,0.027203,0.022541,0.016961,0.027418,0.021692,0.017372,0.019103,0.011734,0.000001,TRIDGZT128F428B9F5
3,0.018246,0.008646,0.021885,0.041223,0.004092,0.080736,0.041131,0.051823,0.020586,0.033808,...,0.009745,0.006665,0.010780,0.003438,0.003464,0.003668,0.004031,0.001271,0.000001,TRHNLNG128F42717FF
4,0.012510,0.018594,0.027447,0.036388,0.023727,0.038141,0.031223,0.038639,0.025802,0.022678,...,0.060113,0.062213,0.075493,0.061272,0.025676,0.020332,0.020932,0.011308,0.002284,TRCNVJH128F427213A
5,0.015173,0.024388,0.017414,0.014775,0.009949,0.007749,0.013393,0.019128,0.033999,0.025982,...,0.027453,0.017317,0.033406,0.022561,0.006079,0.007488,0.002610,0.002452,0.000001,TRKBNOF12903C9A1D0
6,0.030123,0.029823,0.017036,0.010914,0.009533,0.033847,0.046585,0.045769,0.032532,0.028118,...,0.039497,0.046678,0.021754,0.019527,0.028064,0.025103,0.014041,0.005553,0.000001,TRRKOTO128F427F068
7,0.012157,0.028668,0.031598,0.041904,0.025031,0.037941,0.010480,0.016895,0.014114,0.011265,...,0.014447,0.008175,0.012875,0.006476,0.012686,0.004745,0.002044,0.001856,0.000024,TRSXPJU128F429B580
8,0.005166,0.009210,0.020146,0.012968,0.034602,0.031521,0.028261,0.027158,0.031296,0.022515,...,0.057038,0.061210,0.056427,0.040610,0.039139,0.049079,0.035069,0.017533,0.000001,TRFQFHW128F9334372
9,0.011165,0.015923,0.019574,0.009199,0.020257,0.022547,0.024160,0.022785,0.020751,0.021249,...,0.040683,0.033287,0.021351,0.022602,0.012404,0.012053,0.007244,0.002445,0.000001,TRQPSBI128F14AFB5A

## Example 3: msd-marsyas-timbral-v1.0.attributes

In [106]:

# Load the Marsyas Timbral attribute file 
df_attr = spark.read.option("header", "false").csv("wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-marsyas-timbral-v1.0.attributes.csv")

# Show the first few rows to inspect the feature names and types
show_as_html(df_attr)

                                                 _c0   _c1
0  Mean_Acc5_Mean_Mem20_ZeroCrossings_HopSize512_...  real
1  Mean_Acc5_Mean_Mem20_Centroid_Power_powerFFT_W...  real
2  Mean_Acc5_Mean_Mem20_Rolloff_Power_powerFFT_Wi...  real
3  Mean_Acc5_Mean_Mem20_Flux_Power_powerFFT_WinHa...  real
4  Mean_Acc5_Mean_Mem20_MFCC0_Power_powerFFT_WinH...  real
5  Mean_Acc5_Mean_Mem20_MFCC1_Power_powerFFT_WinH...  real
6  Mean_Acc5_Mean_Mem20_MFCC2_Power_powerFFT_WinH...  real
7  Mean_Acc5_Mean_Mem20_MFCC3_Power_powerFFT_WinH...  real
8  Mean_Acc5_Mean_Mem20_MFCC4_Power_powerFFT_WinH...  real
9  Mean_Acc5_Mean_Mem20_MFCC5_Power_powerFFT_WinH...  real

## msd-marsyas-timbral-v1.0.attributes.csv

In [107]:

# Load Marsyas Timbral

marsyas_schema = create_audio_schema('wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-marsyas-timbral-v1.0.attributes.csv')
df_marsyas = load_audio_feature('wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-marsyas-timbral-v1.0.csv', marsyas_schema)

show_as_html(df_marsyas, 10)

,Mean_Acc5_Mean_Mem20_ZeroCrossings_HopSize512_WinSize512_Sum_AudioCh0,Mean_Acc5_Mean_Mem20_Centroid_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0,Mean_Acc5_Mean_Mem20_Rolloff_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0,Mean_Acc5_Mean_Mem20_Flux_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0,Mean_Acc5_Mean_Mem20_MFCC0_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0,Mean_Acc5_Mean_Mem20_MFCC1_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0,Mean_Acc5_Mean_Mem20_MFCC2_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0,Mean_Acc5_Mean_Mem20_MFCC3_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0,Mean_Acc5_Mean_Mem20_MFCC4_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0,Mean_Acc5_Mean_Mem20_MFCC5_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0,...,Std_Acc5_Std_Mem20_PeakRatio_Chroma_D_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0,Std_Acc5_Std_Mem20_PeakRatio_Chroma_D#_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0,Std_Acc5_Std_Mem20_PeakRatio_Chroma_E_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0,Std_Acc5_Std_Mem20_PeakRatio_Chroma_F_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0,Std_Acc5_Std_Mem20_PeakRatio_Chroma_F#_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0,Std_Acc5_Std_Mem20_PeakRatio_Chroma_G_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0,Std_Acc5_Std_Mem20_PeakRatio_Chroma_G#_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0,Std_Acc5_Std_Mem20_PeakRatio_Average_Chroma_A_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0,Std_Acc5_Std_Mem20_PeakRatio_Minimum_Chroma_A_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0,track_id
0,0.112178,0.088561,0.210064,0.094495,-43.977375,3.548018,0.346619,0.580689,-0.226928,0.218630,...,0.000976,0.001009,0.001089,0.001077,0.001037,0.000982,0.001076,0.277586,20.106226,TRSUFWB128F4255BAE
1,0.133675,0.100968,0.229477,0.087755,-42.694424,3.856577,-0.623697,0.510768,0.157851,-0.191616,...,0.000490,0.000480,0.000506,0.000496,0.000461,0.000448,0.000425,0.256402,2.877227,TRSUFSW128F4284B04
2,0.198948,0.177070,0.292963,0.087348,-38.523918,0.690861,-2.264458,1.314971,0.207455,0.143965,...,0.000351,0.000282,0.000288,0.000292,0.000281,0.000289,0.000375,0.080737,0.524488,TRSUFUP128F42561A2
3,0.086491,0.061144,0.132627,0.094506,-43.728943,3.964348,0.943620,1.687271,0.441880,0.541842,...,0.001156,0.001039,0.000951,0.000896,0.000822,0.000770,0.000847,0.277738,7.509386,TRSUFWL128F42956C9
4,0.170560,0.206775,0.451917,0.108458,-62.959637,1.115836,0.030579,-0.110063,-0.177790,0.222752,...,0.001632,0.001724,0.001587,0.001472,0.001094,0.001588,0.001523,0.512680,80.313904,TRSUFQR12903CD493C
5,0.151466,0.108977,0.262887,0.083422,-36.271229,3.478046,-0.382493,0.235853,-0.560301,-0.025379,...,0.000515,0.000525,0.000610,0.000541,0.000504,0.000523,0.000459,0.122107,0.483312,TRSUFHU12903CD842F
6,0.157378,0.123143,0.297925,0.097529,-42.808990,2.122223,-0.139964,1.220489,0.418734,0.426640,...,0.002093,0.002092,0.002031,0.001923,0.001749,0.001572,0.001424,0.181828,1.447693,TRSUQWS128F4288B48
7,0.089715,0.068383,0.127582,0.083627,-48.063675,4.515956,-0.742087,0.692391,0.242253,0.726215,...,0.000117,0.000110,0.000155,0.000166,0.000158,0.000094,0.000091,0.328613,6.928565,TRSUQVH12903CB2BFE
8,0.081881,0.059107,0.134811,0.086008,-42.227097,4.594910,0.353708,1.388084,0.330637,0.638689,...,0.000813,0.000744,0.000802,0.000882,0.000708,0.000618,0.000723,0.143789,1.665064,TRSUQCO128F9303B4C
9,0.078381,0.059711,0.118103,0.092642,-50.912579,5.738254,0.715501,0.261605,0.339573,-0.061473,...,0.000338,0.000296,0.000285,0.000201,0.000112,0.000090,0.000101,0.310401,12.070976,TRSUQBM128F148CF83

In [108]:

df_marsyas.printSchema()

root
 |-- Mean_Acc5_Mean_Mem20_ZeroCrossings_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_Centroid_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_Rolloff_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_Flux_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_MFCC0_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_MFCC1_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_MFCC2_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_MFCC3_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_MFCC4_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_MFCC5_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_MFCC6_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_MFCC7_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_MFCC8_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_MFCC9_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_MFCC10_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_MFCC11_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_MFCC12_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_PeakRatio_Chroma_A_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_PeakRatio_Chroma_A#_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_PeakRatio_Chroma_B_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_PeakRatio_Chroma_C_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_PeakRatio_Chroma_C#_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_PeakRatio_Chroma_D_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_PeakRatio_Chroma_D#_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_PeakRatio_Chroma_E_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_PeakRatio_Chroma_F_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_PeakRatio_Chroma_F#_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_PeakRatio_Chroma_G_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_PeakRatio_Chroma_G#_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_PeakRatio_Average_Chroma_A_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Mean_Mem20_PeakRatio_Minimum_Chroma_A_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_ZeroCrossings_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_Centroid_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_Rolloff_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_Flux_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_MFCC0_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_MFCC1_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_MFCC2_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_MFCC3_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_MFCC4_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_MFCC5_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_MFCC6_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_MFCC7_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_MFCC8_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_MFCC9_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_MFCC10_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_MFCC11_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_MFCC12_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_PeakRatio_Chroma_A_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_PeakRatio_Chroma_A#_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_PeakRatio_Chroma_B_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_PeakRatio_Chroma_C_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_PeakRatio_Chroma_C#_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_PeakRatio_Chroma_D_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_PeakRatio_Chroma_D#_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_PeakRatio_Chroma_E_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_PeakRatio_Chroma_F_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_PeakRatio_Chroma_F#_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_PeakRatio_Chroma_G_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_PeakRatio_Chroma_G#_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_PeakRatio_Average_Chroma_A_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Mean_Acc5_Std_Mem20_PeakRatio_Minimum_Chroma_A_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_ZeroCrossings_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_Centroid_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_Rolloff_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_Flux_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_MFCC0_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_MFCC1_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_MFCC2_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_MFCC3_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_MFCC4_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_MFCC5_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_MFCC6_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_MFCC7_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_MFCC8_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_MFCC9_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_MFCC10_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_MFCC11_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_MFCC12_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_PeakRatio_Chroma_A_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_PeakRatio_Chroma_A#_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_PeakRatio_Chroma_B_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_PeakRatio_Chroma_C_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_PeakRatio_Chroma_C#_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_PeakRatio_Chroma_D_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_PeakRatio_Chroma_D#_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_PeakRatio_Chroma_E_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_PeakRatio_Chroma_F_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_PeakRatio_Chroma_F#_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_PeakRatio_Chroma_G_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_PeakRatio_Chroma_G#_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_PeakRatio_Average_Chroma_A_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Mean_Mem20_PeakRatio_Minimum_Chroma_A_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_ZeroCrossings_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_Centroid_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_Rolloff_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_Flux_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_MFCC0_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_MFCC1_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_MFCC2_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_MFCC3_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_MFCC4_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_MFCC5_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_MFCC6_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_MFCC7_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_MFCC8_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_MFCC9_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_MFCC10_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_MFCC11_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_MFCC12_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_PeakRatio_Chroma_A_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_PeakRatio_Chroma_A#_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_PeakRatio_Chroma_B_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_PeakRatio_Chroma_C_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_PeakRatio_Chroma_C#_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_PeakRatio_Chroma_D_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_PeakRatio_Chroma_D#_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_PeakRatio_Chroma_E_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_PeakRatio_Chroma_F_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_PeakRatio_Chroma_F#_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_PeakRatio_Chroma_G_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_PeakRatio_Chroma_G#_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_PeakRatio_Average_Chroma_A_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- Std_Acc5_Std_Mem20_PeakRatio_Minimum_Chroma_A_Power_powerFFT_WinHamming_HopSize512_WinSize512_Sum_AudioCh0: float (nullable = true)
 |-- track_id: string (nullable = true)

In [ ]:
# Run this cell before closing the notebook or kill your spark application by hand using the link in the Spark UI

stop_spark()